apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.npm.containerName }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
    volumeName: {{ .Values.npm.containerName }}-data-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.npm.containerName }}-letsencrypt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: {{ .Values.npm.containerName }}-letsencrypt-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.containerName }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
    volumeName: {{ .Values.npm.containerName }}-db-pv