apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.npm.containerName }}
spec:
  selector:
    app: {{ .Values.npm.containerName }}
  ports:
    - name: http
      port: {{ .Values.service.ports.httpPort }}
      targetPort: 80
    - name: https
      port: {{ .Values.service.ports.httpsPort }}
      targetPort: 443
    - name: admin
      port: {{ .Values.service.ports.adminPort }}
      targetPort: 81
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.containerName }}
spec:
  selector:
    app: {{ .Values.db.containerName }}
  ports:
    - port: {{ .Values.db.DB_MYSQL_PORT }}
      targetPort: 3306